/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2020-08-18 06:54:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/template/header.jspf", Long.valueOf(1597718856504L));
    _jspx_dependants.put("/template/footer.jspf", Long.valueOf(1597718856488L));
    _jspx_dependants.put("/template/menu.jspf", Long.valueOf(1597718856513L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("\r\n");
      out.write("    <title> Title </title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/template.css\"/>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Noto+Sans+KR:wght@100;500&display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery.bxslider.css\"/>\r\n");
      out.write("    <style rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("        #content{\r\n");
      out.write("          height: 1400px;\r\n");
      out.write("        }\r\n");
      out.write("        .slider>div>img{\r\n");
      out.write("            margin-top: 100px;\r\n");
      out.write("            \r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("        }\r\n");
      out.write("        .login{\r\n");
      out.write("        \tborder:1px solid;\r\n");
      out.write("        \ttext-align:center;\r\n");
      out.write("        \tmargin-right:300px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("            border-color: silver;\r\n");
      out.write("            float: right;\r\n");
      out.write("            width: 280px;\r\n");
      out.write("            background-color: #F5F5F5;\r\n");
      out.write("            border-radius:5px;\r\n");
      out.write("        }\r\n");
      out.write("        .login>h2{\r\n");
      out.write("        \tmargin:10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .btn{\r\n");
      out.write("        \tmargin:10px;\r\n");
      out.write("        \tborder:none;\r\n");
      out.write("            border-radius:10px;\r\n");
      out.write("            background-color: black;\r\n");
      out.write("            color: white;\r\n");
      out.write("            width: 230px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .btn>a{\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        .btn>a:hover{\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("        #id{\r\n");
      out.write("        \tmargin-left:15px;\r\n");
      out.write("        }\r\n");
      out.write("        #id,#password{\r\n");
      out.write("        \tpadding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-1.12.4.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.bxslider.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/menu.js\"></script>\r\n");
      out.write("   ");
 
   		com.bit.model.dto.StudentDto stuBean = (com.bit.model.dto.StudentDto)request.getAttribute("stuBean"); 
   		com.bit.model.dto.EmployeeDto empBean = (com.bit.model.dto.EmployeeDto)request.getAttribute("empBean");
	
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("      $('.slider').bxSlider({\r\n");
      out.write("          mode:'fade',\r\n");
      out.write("          captions:true\r\n");
      out.write("          \r\n");
      out.write("       });\r\n");
      out.write("            \r\n");
      out.write("      $('form').submit(function(){\r\n");
      out.write("         var id = $('#id').val();\r\n");
      out.write("         var password = $('#password').val();\r\n");
      out.write("         \r\n");
      out.write("         if(id == '') {\r\n");
      out.write("             alert(\"아이디를 입력해주세요\");\r\n");
      out.write("                $(\"#id\").focus();\r\n");
      out.write("         }\r\n");
      out.write("         if(id != '' && password== '') {\r\n");
      out.write("             alert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("                $(\"#password\").focus();\r\n");
      out.write("         }\r\n");
      out.write("         if(id != '' && password != '') {\r\n");
      out.write("            var param = \"id=\" + id + \"&password=\" + password;\r\n");
      out.write("            $.ajax({\r\n");
      out.write("               \"type\" : \"post\",\r\n");
      out.write("                   \"data\" : param,\r\n");
      out.write("                   \"url\" : \"login.bit\",\r\n");
      out.write("                   \"success\" : function(data) {\r\n");
      out.write("                \t var fail =$(data).find('fail').text();\r\n");
      out.write("\t\t\t\t\t if(fail == 'loginFail') {\r\n");
      out.write("                         alert(\"존재하지 않는 계정입니다.\\n아이디와 비밀번호를 다시 입력해주세요.\");   \r\n");
      out.write("                     }else{\r\n");
      out.write("                       window.location.replace(\"index.bit\"); \r\n");
      out.write("                     }\r\n");
      out.write("                   }, // success\r\n");
      out.write("                   \"error\": function(request, status, error){\r\n");
      out.write("                       //alert(\"code:\" + request.status + \"\\n\" + \"error:\" + error);\r\n");
      out.write("                      alert(\"존재하지 않는 계정입니다.\\n아이디와 비밀번호를 다시 입력해주세요.\");\r\n");
      out.write("                   } // error\r\n");
      out.write("            }); // ajax\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         return false;   \r\n");
      out.write("      }); // submit\r\n");
      out.write("            \r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write(" <div id=\"header\">\r\n");
      out.write(" \t    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div><a href=\"index.bit\"><img src=\"img/logo.png\" /></a></div><div><img src=\"img/top.png\"/></div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<div id=\"menu\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <ol>비트 캠프\r\n");
      out.write("                    <li><a href=\"intro.bit\">비트 캠프 소개</a></li>\r\n");
      out.write("                    <li><a href=\"teacher.bit\">강사진 소개</a></li>\r\n");
      out.write("                    <li><a href=\"map.bit\">오시는 길</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("                <ol>교육 소개\r\n");
      out.write("                    <li><a href=\"subject.bit\">교육 과정 소개</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("                <ol>교육 과정\r\n");
      out.write("                    <li><a href=\"courselist.bit\">모집중인 과정</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("                <ol>취업 지원 센터\r\n");
      out.write("                    <li><a href=\"recruit.bit\">취업 지원 센터</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>");
      out.write("\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("   <!--content start  -->\r\n");
      out.write("   <div class=\"slider\">\r\n");
      out.write("        <div><img src=\"img/1.jpg\"/></div>\r\n");
      out.write("        <div><img src=\"img/2.jpg\"/></div>\r\n");
      out.write("        <div><img src=\"img/3.jpg\"/></div>\r\n");
      out.write("        <div><img src=\"img/4.jpg\"/></div>\r\n");
      out.write("   </div>\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   <!--content end  -->\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("     <img src=\"img/logo.png\"/>\r\n");
      out.write("\t비트캠프 제주특별자치도 서귀포시 안덕면 신화역사로 15｜ 사업자등록번호 : 214-85-24928<br/>\r\n");
      out.write("   (주)비트컴퓨터 제주 대표이사 : 조현정 / 문의 : 064-794-5312 / 팩스 : 064-6007-1245<br/>\r\n");
      out.write("   통신판매업 신고번호 : 제 서초-00098호 / 개인정보보호관리책임자 : 최종진<br/>\r\n");
      out.write("   Copyright (c) 비트캠프 All rights reserved.\r\n");
      out.write("       \r\n");
      out.write("   </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /template/header.jspf(6,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuBean ne null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuBean.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("님&nbsp;|\r\n");
          out.write("    <a href=\"logout.bit\">로그아웃&nbsp;|</a> \r\n");
          out.write("    <a href=\"mypage.bit\">마이페이지</a>\r\n");
          out.write("    </span>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /template/header.jspf(12,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empBean ne null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empBean.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\r\n");
          out.write("   <a href=\"logout.bit\">로그아웃&nbsp;|</a> \r\n");
          out.write("   <a href=\"ahome.bit\">마이페이지</a>\r\n");
          out.write("   </span>\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /template/header.jspf(18,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuBean eq null and empBean eq null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <span>\r\n");
          out.write("\t <a href=\"index.bit\">로그인&nbsp;|</a>\r\n");
          out.write("\t <a href=\"join.bit\">회원가입</a>\r\n");
          out.write("   </span>\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /index.jsp(135,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuBean eq null and empBean eq null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("         <form action=\"login.bit\" method=\"post\">\r\n");
          out.write("            <div class=\"login\">\r\n");
          out.write("                   <h2>비트캠프 로그인</h2>\r\n");
          out.write("                   <br/>\r\n");
          out.write("                   <div>\r\n");
          out.write("                      <label for=\"id\">아이디</label>\r\n");
          out.write("                    <input type=\"text\" id=\"id\" placeholder=\"아이디를 입력하세요\" />\r\n");
          out.write("                 <br/><br/>\r\n");
          out.write("                    <label for=\"password\">비밀번호</label>\r\n");
          out.write("                    <input type=\"password\" id=\"password\" placeholder=\"비밀번호를 입력하세요\"/><br/><br/>\r\n");
          out.write("                   </div>\r\n");
          out.write("                <div>\r\n");
          out.write("                 <button class=\"btn\" type=\"submit\">로그인</button>\r\n");
          out.write("                 <button class=\"btn\" type=\"button\"><a href=\"\">회원가입</a></button>\r\n");
          out.write("                 <button class=\"btn\" type=\"button\"><a href=\"\">아이디 / 비밀번호 찾기</a></button>          \r\n");
          out.write("                </div>\r\n");
          out.write("          </div>\r\n");
          out.write("      </form>\r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /index.jsp(155,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuBean ne null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("         <div class=\"login\">\r\n");
          out.write("            <h2>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuBean.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("님 환영합니다.</h2>\r\n");
          out.write("            <button class=\"btn\" type=\"button\"><a href=\"mypage.bit\" class=\"an\">마이페이지</a></button>\r\n");
          out.write("            <button class=\"btn\" type=\"button\"><a href=\"logout.bit\" class=\"an\">로그아웃</a></button>\r\n");
          out.write("         </div>\r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /index.jsp(162,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empBean ne null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("         <div class=\"login\">\r\n");
          out.write("            <h2>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empBean.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("님 환영합니다.</h2>\r\n");
          out.write("            <button class=\"btn\" type=\"button\"><a href=\"admin/ahome.bit\" class=\"an\">관리자페이지</a></button>\r\n");
          out.write("            <button class=\"btn\" type=\"button\"><a href=\"logout.bit\" class=\"an\">로그아웃</a></button>\r\n");
          out.write("         </div>\r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }
}
