/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2020-08-19 01:14:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class intro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/template/header.jspf", Long.valueOf(1597718856504L));
    _jspx_dependants.put("/template/footer.jspf", Long.valueOf(1597718856488L));
    _jspx_dependants.put("/template/menu.jspf", Long.valueOf(1597718856513L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("\r\n");
      out.write("    <title> Title </title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/template.css\"/>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Noto+Sans+KR:wght@100;500&display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery.bxslider.css\"/>\r\n");
      out.write("    <style rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("        *{\r\n");
      out.write("        \tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        #content{\r\n");
      out.write("          height: 1700px;\r\n");
      out.write("          width: 1500px;\r\n");
      out.write("          padding-top: 100px;\r\n");
      out.write("          text-align: center;\r\n");
      out.write("          padding-left: 180px;\r\n");
      out.write("        }\r\n");
      out.write("        .Intro1,Intro2{\r\n");
      out.write("        \twidth: 700px;\r\n");
      out.write("        \theight: 700px;\r\n");
      out.write("        }\r\n");
      out.write("        .Intro1{\r\n");
      out.write("        \twidth: 800px;\r\n");
      out.write("        }\r\n");
      out.write("       \t.slider>img{\r\n");
      out.write("       \t\tmargin-left:320px;\r\n");
      out.write("            max-width:750px;\r\n");
      out.write("            max-height:750px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-1.12.4.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.bxslider.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/menu.js\"></script>\r\n");
      out.write("    <script>  \r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    \t$('.slider').bxSlider({\r\n");
      out.write("    \t\tmode:'fade',\r\n");
      out.write("    \t\tcaptions:true\t\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write(" <div id=\"header\">\r\n");
      out.write(" \t    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div><a href=\"index.bit\"><img src=\"img/logo.png\" /></a></div><div><img src=\"img/top.png\"/></div>\r\n");
      out.write("    </div>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<div id=\"menu\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <ol>비트 캠프\r\n");
      out.write("                    <li><a href=\"intro.bit\">비트 캠프 소개</a></li>\r\n");
      out.write("                    <li><a href=\"teacher.bit\">강사진 소개</a></li>\r\n");
      out.write("                    <li><a href=\"map.bit\">오시는 길</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("                <ol>교육 소개\r\n");
      out.write("                    <li><a href=\"subject.bit\">교육 과정 소개</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("                <ol>교육 과정\r\n");
      out.write("                    <li><a href=\"courselist.bit\">모집중인 과정</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("                <ol>취업 지원 센터\r\n");
      out.write("                    <li><a href=\"recruit.bit\">취업 지원 센터</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>");
      out.write("\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("\t<!--content start  -->\r\n");
      out.write("\t\r\n");
      out.write("        <img src=\"img/main-intro.jpg\"/>\r\n");
      out.write("        \r\n");
      out.write("        <hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    <h2>대표 인사말</h2>\r\n");
      out.write("\t        \t<span class=\"Intro1\">\r\n");
      out.write("\t        \t\r\n");
      out.write("조현정회장<br>\r\n");
      out.write("최신 소프트웨어를 개발하고 이를 바탕으로<br>\r\n");
      out.write("SI사업과 교육사업을 병행하고 있는 교육센터입니다.<br>\r\n");
      out.write("빠르게 발전하는 IT기술분야에 최적의 교육해법을 제안하여 준비된 인재를<br>\r\n");
      out.write("양성하는 IT전문 교육센터입니다. IT전문가를 향한 꿈, IT분야 취업의 희망!<br>\r\n");
      out.write("교육센터 전 임직원이 최선을 다해 지원해드리겠습니다.<br><br><br>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<span class=\"Intro2\">\r\n");
      out.write("\t\t\t\t시스템 통합 관련 프로젝트와 소프트웨어 개발·보급·자문, IT관련 소프트웨어 전문 인력 양성에 중점을 두고 있습니다.\r\n");
      out.write("\r\n");
      out.write("스마트폰 개발 기술 및 자바, Web2.0 기술 등을 활용한 시스템 통합과 소프트웨어, 솔루션 개발을 맡아<br>\r\n");
      out.write("전방에서 진두지휘하고 그것을 바탕으로 비트캠프를 운영하고 있습니다.<br><br>\r\n");
      out.write("\r\n");
      out.write("특히, 개발자 커뮤니티 대표들과의 최신 서적 저자 등 유망 강사진을 통해 최적의 교육솔루션을 제공하고 있으며, 노동부와 중기청,<br>\r\n");
      out.write("한국산업인력공단, 한국산업기술진흥원, 정보통신산업진흥원 등으로부터 인정받아 국내 및 해외취업 과정을 정부지원 하에<br>\r\n");
      out.write("수행하고 있습니다. 한편, 현대해상 프로젝트, 하이닉스, 마포구청 등 대규모 SI개발 프로젝트에 우수인력을 파견하고 있고,<br>\r\n");
      out.write("이렇게 다양한 SI영역에서의 사업은 비트캠프 출신의 수료생들을 적극 활용하고 있습니다. 실무위주의 교육을 받은 수료생들은<br>\r\n");
      out.write("채용은 물론 미취업 시 실무 프로젝트 투입기회 제공 등 다각도의 지원을 하고 있습니다.<br><br>\r\n");
      out.write("\r\n");
      out.write("교육센터는 \"회사 구성원 대부분인 IT서적 저자, 개발자, 전문교육 수료생 출신이기 때문에 전문성과<br>\r\n");
      out.write("결속력이 뛰어나다\"고 생각합니다. 앞으로 우리 교육센터는 \"실무중심 교육 및 신기술을 선도하는 교육센터\"를 만들어가겠습니다.<br><br>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t       \t\t<h3>회사 연혁</h3>\r\n");
      out.write("\t\t\t\t<div class=\"slider\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/history0.jpg\"/>\r\n");
      out.write("\t\t\t\t\t<img src=\"img/history1.jpg\"/>\r\n");
      out.write("\t\t\t\t\t<img src=\"img/history2.jpg\"/>\r\n");
      out.write("\t\t\t\t\t<img src=\"img/history3.jpg\"/>\r\n");
      out.write("\t\t\t\t\t<img src=\"img/history4.jpg\"/>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("\t<!--content end  -->\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("     <img src=\"img/logo.png\"/>\r\n");
      out.write("\t비트캠프 제주특별자치도 서귀포시 안덕면 신화역사로 15｜ 사업자등록번호 : 214-85-24928<br/>\r\n");
      out.write("   (주)비트컴퓨터 제주 대표이사 : 조현정 / 문의 : 064-794-5312 / 팩스 : 064-6007-1245<br/>\r\n");
      out.write("   통신판매업 신고번호 : 제 서초-00098호 / 개인정보보호관리책임자 : 최종진<br/>\r\n");
      out.write("   Copyright (c) 비트캠프 All rights reserved.\r\n");
      out.write("       \r\n");
      out.write("   </div>");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</body></html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /template/header.jspf(6,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuBean ne null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuBean.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("님&nbsp;|\r\n");
          out.write("    <a href=\"logout.bit\">로그아웃&nbsp;|</a> \r\n");
          out.write("    <a href=\"mypage.bit\">마이페이지</a>\r\n");
          out.write("    </span>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /template/header.jspf(12,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empBean ne null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empBean.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\r\n");
          out.write("   <a href=\"logout.bit\">로그아웃&nbsp;|</a> \r\n");
          out.write("   <a href=\"ahome.bit\">마이페이지</a>\r\n");
          out.write("   </span>\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /template/header.jspf(18,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stuBean eq null and empBean eq null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <span>\r\n");
          out.write("\t <a href=\"index.bit\">로그인&nbsp;|</a>\r\n");
          out.write("\t <a href=\"join.bit\">회원가입</a>\r\n");
          out.write("   </span>\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
